# std = "luajit"

[config]
global_usage = { ignore_pattern = "^(wezterm|vim)$" }

[rules]
undefined_variable = "warn"
if_same_then_else = "allow"
incorrect_standard_library_use = "allow"
mixed_table = "allow"
multiple_statements = "allow"
